### ISSUE TITLE
Docstrings not allowed in Interface subclasses.

### ISSUE THREAD

**Issue by benwah** [marrow/interface#1]
# Traceback

```
Traceback (most recent call last):
  File "core.py", line 7, in <module>
    class TempStore(Interface):
  File "/.../marrow/interface/core.py", line 29, in __new__
    type(value).__name__, key))
TypeError: Interfaces must only contain Attribute instances, not a str named __doc__.
```
# Test Case

```
class Example(Interface):
    """Turn this into an interface?"""
    __init__ = Method(args=0)
    bob = Method(args=2, kwargs=1)
    dole = Method(args=1)
```

**Comment by amcgregor** [comment]
Potentially solved in 9bef125df9.
